server:
  port: 9999

logging:
  file:
    name: log.log
  level:
    root: info

spring:
  data:
    mongodb:
      # uri: mongodb://root:23456@127.0.0.1:27017/xx_system?authSource=admin
#      uri: mongodb://127.0.0.1:27017/xx_system
      uri: mongodb://1.14.64.132:27017/xx_system

  redis:
#    host: 127.0.0.1
    host: 1.14.64.132
    port: 6379
    database: 8
    connect-timeout: 10000
    timeout: 10000

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

xx-system:
  swagger:
    enable: true
  # 记住我得有效期